name: scChIPseq-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - bioconda::multiqc
  - bioconda::bowtie2
  - bioconda::fastx_toolkit
  - bioconda::star
  - bioconda::seqtk
  - bioconda::samtools
  - conda-forge::more-itertools
  - bioconda::bedtools
  - bioconda::deeptools=3.5.1

  ## python
  - bioconda::pysam
  - bioconda::bx-python
