#
# scChIP-seq config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:
    scChIPseq_general_table:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: "For a correct sample, at least 500 cells should have more than 1000 reads and the median number of reads for these cells should be at least 1100.\n  At least 60% of aligned reads and 15% of aligned and barcoded reads are expected.\n Finaly, a minimum of 3 to 5% of unique reads is needed."
        plot_type: 'table'
        pconfig:
            id: 'scChIPseq_general_table'
            save_file: true
            col1_header: 'Sample ID'
        headers:
            Sample_name:
              title: 'Sample Name'
              scale: false
              placement: 2000
            Cells:
              description: 'Cells'
              format: '{:,.0f}'
              max: 100
              min: 0
              scale: 'YlGn'
              placement: 3000
            Cells>1000reads:
              description: 'Cells>1000reads'
              max: 100
              min: 0
              scale: 'YlGn'
              placement: 4000
            Median (cells>1000reads):
              description: 'Median(cells>1000reads)'
              max: 100
              min: 0
              scale: 'YlGn'
              placement: 5000
            Aligned:
              description: 'Aligned (%)'
              format: '{:,.0f}'
              max: 100
              min: 0
              suffix: '%'
              scale: 'YlGn'
              placement: 6000
            Aligned & Barcoded:
              description: 'Aligned & Barcoded (%)'
              format: '{:,.0f}'
              max: 100
              min: 0
              suffix: '%'
              scale: 'YlGn'
              placement: 7000
            Unique Reads:
              description: 'Unique Reads (%)'
              format: '{:,.0f}'
              max: 100
              min: 0
              suffix: '%'
              scale: 'YlGn'
              placement: 8000
            
    scChIPseq_barcode:
        id: 'scChIPseq_barcode'
        file_format: 'csv'
        description: 'If 40% or more sequences are correctly barcoded, the barcoding step went well. If it is between 20% and 40% be carrefull and if it less, barcoding step went wrong.'
        section_name: 'Barcode Matching'
        plot_type: 'bargraph'
        pconfig:
            title: 'Barcode Mapping'
            ylab: '# Reads'
            cpswitch_counts_label': 'Number of Reads'

    scChIPseq_alignments:
        id: 'scChIPseq_alignments'
        file_format: 'csv'
        description: 'Arround 5-10% of deduplicated reads (at least 5%), arround 40-50% of RT & PCR duplicates (no more than 50%) and arround 10-15% of window duplicates (no more than 15%) are expected.'
        section_name: Alignment Scores'
        plot_type: 'bargraph'
        pconfig:
            id: 'scChIPseq_alignments_plot'
            title: 'scChIPseq: Barcode Mapping'
            ylab: '# Reads'
            cpswitch_counts_label': 'Number of Reads'

    umiDistrib:
      file_format: 'csv'
      section_name: 'Read distributions across cells'
      description: 'Overview of read distribution across cells.  If you observed a bimodal distribution, your data may contain empty droplets as first pics represent the proportion of cells having a low number of reads. Higher these pics are, higher the number of cells having a low number of reads is. This information can be used to define a threshold to remove empty droplets identified by a low number of reads.  If you do not see a bimodal distribution, your data have probably been filtred on a minimum reads per cell, usually 1000.'
      plot_type: 'linegraph'
      pconfig:
        id: 'umiDistrib'
        title: 'Weighted Histogram'
        ylab: 'Sum of reads per bin'
        xlab: 'log10(#Reads/cell)'

sp:
  scChIPseq_general_table:
      fn: 'scChIPseq_table.csv'
  scChIPseq_barcode:
      fn: 'scChIPseq_barcode.csv'
  scChIPseq_alignments:
      fn: 'scChIPseq_alignments.csv'
  umiDistrib:
      fn: '*_distDF.mqc'


###############################
## Modules 

module_order:
  - bowtie2:
     name: 'Bowtie2'
     info: 'Alignment results of the three barcode indexes. Index1 should be arround 75%, index2 arround 50% and index3 arround 40%.'
  - star:
     name: 'STAR'
     info: "Alignement is made on all the initial reads. \nReads passing alignment are uniquely mapped or mapped to multiple loci.\nIf this two made up to 60%, the alignemnt is a success. If they made between 60 and 40%, be carrefull and if they made less than 40% the sample may have a problem."
#############################
## Display

report_section_order:
  scChIPseq_general_table:
    order: 1
  bowtie2:
    order: -300
  scChIPseq_barcode:
    order: -400
  star:
    order: -500
  scChIPseq_alignments:
    order: -600
  umiDistrib:
    order: -700
  scChip-seq_pipeline_software_versions:
    order: -1000
  summary:
    order: -1100

plots_force_interactive: True
