#
# scChIP-seq config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:
    scChIPseq_general_table:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: ''
        plot_type: 'table'
        pconfig:
            id: 'scChIPseq_general_table'
            save_file: true
            col1_header: 'Sample ID'
        headers:
            Sample_name:
              title: 'Sample Name'
              scale: false
            Cells:
              description: 'Cells'
              format: '{:,.0f}'
              max: 100
              min: 0
              scale: 'YlGn'
              placement: 200
            Cells>1000reads:
              description: 'Cells>1000reads'
              format: '{:,.0f}'
              max: 100
              min: 0
              scale: 'YlGn'
              placement: 300
            Median:
              description: 'Median(cells>1000reads)'
              format: '{:,.0f}'
              max: 100
              min: 0
              suffix: '%'
              scale: 'YlGn'
            Aligned:
              description: 'Aligned (%)'
              format: '{:,.0f}'
              max: 100
              min: 0
              suffix: '%'
              scale: 'YlGn'
              placement: 500
            Aligned_Barcoded:
              description: 'Aligned and Barcoded (%)'
              format: '{:,.0f}'
              max: 100
              min: 0
              suffix: '%'
              scale: 'YlGn'
              placement: 600
            Unique_Reads:
              description: 'Unique Reads (%)'
              format: '{:,.0f}'
              max: 100
              min: 0
              suffix: '%'
              scale: 'YlGn'
              placement: 700
            
    scChIPseq_barcode:
        id: 'scChIPseq_barcode'
        file_format: 'csv'
        description: ''
        section_name: 'Barcode Matching'
        plot_type: 'bargraph'
        pconfig:
            title: 'Barcode Mapping'
            ylab: '# Reads'
            cpswitch_counts_label': 'Number of Reads'

    scChIPseq_alignments:
        id: 'scChIPseq_alignments'
        file_format: 'csv'
        section_name: Alignment Scores'
        plot_type: 'bargraph'
        pconfig:
            id: 'scChIPseq_alignments_plot'
            title: 'scChIPseq: Barcode Mapping'
            ylab: '# Reads'
            cpswitch_counts_label': 'Number of Reads'

sp:
  scChIPseq_general_table:
      fn: 'scChIPseq_table.csv'
  scChIPseq_barcode:
      fn: 'scChIPseq_barcode.csv'
  scChIPseq_alignments:
      fn: 'scChIPseq_alignments.csv'


###############################
## Modules 

module_order:
  - bowtie2:
     name: 'Bowtie2'
     info: 'Alignment results of the three barcode indexes. Index1 should be arround 75%, index2 arround 50% and index3 arround 40%.'
  
#############################
## Display

report_section_order:
  scChIPseq_general_table:
    order: 1
  bowtie2:
    order: -300
  scChIPseq_barcode:
    order: -400
  star:
    order: -500
  scChIPseq_alignments:
    order: -600
  scChip-seq_pipeline_software_versions:
    order: -1000
  summary:
    order: -1100

plots_force_interactive: True
