#
# scChIP-seq config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:
    scChIPseq_general_table:
        id: 'scChIPseq_general_table'
        file_format: 'csv'
        section_name: 'General Stats'
        plot_type: 'table'
        pconfig:
            id: 'scChIPseq_barcode_plot'
            title: 'Barcode Mapping'
            cpswitch_counts_label': 'Number of Reads'
        headers:
            '%Aligned':
                description: '% Aligned'
                format: '{:,.0f}'
                max: 100
                min: 0
                suffix: '%'
                scale: 'YlGn'
            '%Aligned_Barcoded':
                description: '% Aligned and Barcoded'
                format: '{:,.0f}'
                max: 100
                min: 0
                suffix: '%'
                scale: 'YlGn'
            '%Unique_Reads':
                description: '% Unique Reads'
                format: '{:,.0f}'
                max: 100
                min: 0
                suffix: '%'
                scale: 'YlGn'
            
    scChIPseq_barcode:
        id: 'scChIPseq_barcode'
        file_format: 'csv'
        description: 'Number of barcodes with more than 100 unique reads = 128 <br>Number of barcodes with more than 500 unique reads = 5 <br>Number of barcodes with more than 1000 unique reads = 1 <br>Number of barcodes with more than 1500 unique reads = 0'
        section_name: 'Barcode Matching'
        plot_type: 'bargraph'
        pconfig:
            id: 'scChIPseq_barcode_plot'
            title: 'Barcode Mapping'
            ylab: '# Reads'
            cpswitch_counts_label': 'Number of Reads'

    scChIPseq_alignments:
        id: 'scChIPseq_alignments'
        file_format: 'csv'
        section_name: Alignment Scores'
        plot_type: 'bargraph'
        pconfig:
            id: 'scChIPseq_alignments_plot'
            title: 'scChIPseq: Barcode Mapping'
            ylab: '# Reads'
            cpswitch_counts_label': 'Number of Reads'

sp:
    scChIPseq_general_table:
        fn: '*scChIPseq_table.csv'
    scChIPseq_barcode:
        fn: '*scChIPseq_barcode.csv'
    scChIPseq_alignments:
        fn: '*scChIPseq_alignments.csv'


###############################
## Modules 

module_order:
  - fastqc
  - bowtie1:
      name: 'rRNA Mapping'
      info: 'This section reports the fraction of reads aligned on ribosomal RNAs.'
      target: ''
      path_filters:
        - '*.log'
  - star
  - hisat2
  - tophat
  - rseqc
  - featureCounts
  - HTSeq
  - preseq:
     name: 'Sequencing Complexity'
     info: 'estimates the complexity of a library, showing how many additional unique reads are sequenced for increasing total read count. A shallow curve indicates complexity saturation. The dashed line shows a perfectly complex library where total reads = unique reads. The presented graph shows extrapolated curves up to 200M sequencing reads.'

#############################
## Display

report_section_order:
  stats:
    order: 1
  gene_saturation:
    order: -400
  gene_type:
    order: -500
  DupRadar:
    order: -600 
  sample-pca:
    order: -800
  sample-correlation:
    order: -900
  software_versions:
    order: -1000
  summary:
    order: -1100

plots_force_interactive: True
